export const bankList = [
  {
    value: "Abbey Mortgage Bank",
    slug: "abbey-mortgage-bank",
    code: "801",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Above Only MFB",
    slug: "above-only-mfb",
    code: "51204",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Access Bank",
    slug: "access-bank",
    code: "044",
    longCode: "044150149",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },

  {
    value: "ALAT by WEMA",
    slug: "alat-by-wema",
    code: "035A",
    longCode: "035150103",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Amju Unique MFB",
    slug: "amju-unique-mfb",
    code: "50926",
    longCode: "511080896",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "ASO Savings and Loans",
    slug: "asosavings",
    code: "401",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Bainescredit MFB",
    slug: "bainescredit-mfb",
    code: "51229",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Bowen Microfinance Bank",
    slug: "bowen-microfinance-bank",
    code: "50931",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Carbon",
    slug: "carbon",
    code: "565",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "CEMCS Microfinance Bank",
    slug: "cemcs-microfinance-bank",
    code: "50823",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Citibank Nigeria",
    slug: "citibank-nigeria",
    code: "023",
    longCode: "023150005",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Coronation Merchant Bank",
    slug: "coronation-merchant-bank",
    code: "559",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Ecobank Nigeria",
    slug: "ecobank-nigeria",
    code: "050",
    longCode: "050150010",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Ekondo Microfinance Bank",
    slug: "ekondo-microfinance-bank",
    code: "562",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Eyowo",
    slug: "eyowo",
    code: "50126",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Fidelity Bank",
    slug: "fidelity-bank",
    code: "070",
    longCode: "070150003",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Firmus MFB",
    slug: "firmus-mfb",
    code: "51314",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "First Bank of Nigeria",
    slug: "first-bank-of-nigeria",
    code: "011",
    longCode: "011151003",
    gateway: "ibank",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "First City Monument Bank",
    slug: "first-city-monument-bank",
    code: "214",
    longCode: "214150018",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "FSDH Merchant Bank Limited",
    slug: "fsdh-merchant-bank-limited",
    code: "501",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Globus Bank",
    slug: "globus-bank",
    code: "00103",
    longCode: "103015001",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "GoMoney",
    slug: "gomoney",
    code: "100022",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Guaranty Trust Bank",
    slug: "guaranty-trust-bank",
    code: "058",
    longCode: "058152036",
    gateway: "ibank",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Hackman Microfinance Bank",
    slug: "hackman-microfinance-bank",
    code: "51251",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Hasal Microfinance Bank",
    slug: "hasal-microfinance-bank",
    code: "50383",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Heritage Bank",
    slug: "heritage-bank",
    code: "030",
    longCode: "030159992",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Ibile Microfinance Bank",
    slug: "ibile-mfb",
    code: "51244",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Infinity MFB",
    slug: "infinity-mfb",
    code: "50457",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Jaiz Bank",
    slug: "jaiz-bank",
    code: "301",
    longCode: "301080020",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Kadpoly MFB",
    slug: "kadpoly-mfb",
    code: "50502",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Keystone Bank",
    slug: "keystone-bank",
    code: "082",
    longCode: "082150017",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Kredi Money MFB LTD",
    slug: "kredi-money-mfb",
    code: "50200",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Kuda Bank",
    slug: "kuda-bank",
    code: "50211",
    longCode: "",
    gateway: "digitalbankmandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Lagos Building Investment Company Plc.",
    slug: "lbic-plc",
    code: "90052",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Links MFB",
    slug: "links-mfb",
    code: "50549",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Lotus Bank",
    slug: "lotus-bank",
    code: "303",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Mayfair MFB",
    slug: "mayfair-mfb",
    code: "50563",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Mint MFB",
    slug: "mint-mfb",
    code: "50304",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Paga",
    slug: "paga",
    code: "100002",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "PalmPay",
    slug: "palmpay",
    code: "999991",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Parallex Bank",
    slug: "parallex-bank",
    code: "104",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Parkway - ReadyCash",
    slug: "parkway-ready-cash",
    code: "311",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Paycom",
    slug: "paycom",
    code: "999992",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Petra Mircofinance Bank Plc",
    slug: "petra-microfinance-bank-plc",
    code: "50746",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Polaris Bank",
    slug: "polaris-bank",
    code: "076",
    longCode: "076151006",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Providus Bank",
    slug: "providus-bank",
    code: "101",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "QuickFund MFB",
    slug: "quickfund-mfb",
    code: "51293",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Rand Merchant Bank",
    slug: "rand-merchant-bank",
    code: "502",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Rubies MFB",
    slug: "rubies-mfb",
    code: "125",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Sparkle Microfinance Bank",
    slug: "sparkle-microfinance-bank",
    code: "51310",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Stanbic IBTC Bank",
    slug: "stanbic-ibtc-bank",
    code: "221",
    longCode: "221159522",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Standard Chartered Bank",
    slug: "standard-chartered-bank",
    code: "068",
    longCode: "068150015",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Sterling Bank",
    slug: "sterling-bank",
    code: "232",
    longCode: "232150016",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Suntrust Bank",
    slug: "suntrust-bank",
    code: "100",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "TAJ Bank",
    slug: "taj-bank",
    code: "302",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Tangerine Money",
    slug: "tangerine-money",
    code: "51269",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "TCF MFB",
    slug: "tcf-mfb",
    code: "51211",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Titan Bank",
    slug: "titan-bank",
    code: "102",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Unical MFB",
    slug: "unical-mfb",
    code: "50871",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Union Bank of Nigeria",
    slug: "union-bank-of-nigeria",
    code: "032",
    longCode: "032080474",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "United Bank For Africa",
    slug: "united-bank-for-africa",
    code: "033",
    longCode: "033153513",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Unity Bank",
    slug: "unity-bank",
    code: "215",
    longCode: "215154097",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "VFD Microfinance Bank Limited",
    slug: "vfd",
    code: "566",
    longCode: "",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Wema Bank",
    slug: "wema-bank",
    code: "035",
    longCode: "035150103",
    gateway: null,
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
  {
    value: "Zenith Bank",
    slug: "zenith-bank",
    code: "057",
    longCode: "057150013",
    gateway: "emandate",
    active: true,
    country: "Nigeria",
    currency: "NGN",
    type: "nuban",
  },
];
